export const QUESTIONS: any = {
    quest1: "Medite em:",
    quest2: "2. Qual ensinamento essa passagem traz para você? ",
    quest3: "3. Qual a atividade mais importante que fará hoje com foco no crescimento da área que você escolheu para desenvolver? ",
    quest4: "4. Dentro de seus afazeres no dia de hoje, quais são os 3 mais importantes e que você não pode deixar de realizar? ",
    quest5: "5. O que você vai descartar da sua agenda hoje que está roubando sua atenção e energia?",
    quest6: "6.  Qual ato de serviço você fará hoje sem interesse?",
    quest7: "7.  Pelo que você é grato hoje?",
    quest8: "8.  Avalie seu dia: ",
    quest8_a: "Fez atividade física ?",
    quest8_b: "Leu a Bíblia?",
    quest8_c: "Resolveu problemas",
    quest8_d: "Teve tempo com Deus",
    quest8_e: "Teve tempo com a família",
    quest8_f: "Bebeu entre 3 e 4 litros de água",
    quest8_g: "Sua alimentação foi balanceada",
    quest8_h: "Ensinou algo á alguém hoje",
    quest8_i: "Aprendeu algo novo hoje",
    quest9: "9.  Numa escala de 0% á 100% seu dia foi?",
    quest10: "10. Relacione quais micro resultados você conquistou hoje:",
    quest11: "11. Qual a recompensa que você se deu hoje?",
    quest12: "12. Qual perda teve por não realizar algo que havia planejado?",
    quest13: "13. Avaliação final do dia (descreva com suas palavras):",
};
